//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubwaySite.ServiceReferenceLogic {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Line", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Line : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private bool operabilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SubwaySite.ServiceReferenceLogic.Station[] stationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool operability {
            get {
                return this.operabilityField;
            }
            set {
                if ((this.operabilityField.Equals(value) != true)) {
                    this.operabilityField = value;
                    this.RaisePropertyChanged("operability");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SubwaySite.ServiceReferenceLogic.Station[] stations {
            get {
                return this.stationsField;
            }
            set {
                if ((object.ReferenceEquals(this.stationsField, value) != true)) {
                    this.stationsField = value;
                    this.RaisePropertyChanged("stations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Station : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SubwaySite.ServiceReferenceLogic.Station stationRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SubwaySite.ServiceReferenceLogic.Station stationLeftField;
        
        private bool operabilityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SubwaySite.ServiceReferenceLogic.Station stationRight {
            get {
                return this.stationRightField;
            }
            set {
                if ((object.ReferenceEquals(this.stationRightField, value) != true)) {
                    this.stationRightField = value;
                    this.RaisePropertyChanged("stationRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SubwaySite.ServiceReferenceLogic.Station stationLeft {
            get {
                return this.stationLeftField;
            }
            set {
                if ((object.ReferenceEquals(this.stationLeftField, value) != true)) {
                    this.stationLeftField = value;
                    this.RaisePropertyChanged("stationLeft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool operability {
            get {
                return this.operabilityField;
            }
            set {
                if ((this.operabilityField.Equals(value) != true)) {
                    this.operabilityField = value;
                    this.RaisePropertyChanged("operability");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLogic.WebServiceLogicSoap")]
    public interface WebServiceLogicSoap {
        
        // CODEGEN: Generating message contract since element name getSubwayResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSubway", ReplyAction="*")]
        SubwaySite.ServiceReferenceLogic.getSubwayResponse getSubway(SubwaySite.ServiceReferenceLogic.getSubwayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSubway", ReplyAction="*")]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.getSubwayResponse> getSubwayAsync(SubwaySite.ServiceReferenceLogic.getSubwayRequest request);
        
        // CODEGEN: Generating message contract since element name station_Search from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStation", ReplyAction="*")]
        SubwaySite.ServiceReferenceLogic.getStationResponse getStation(SubwaySite.ServiceReferenceLogic.getStationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStation", ReplyAction="*")]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.getStationResponse> getStationAsync(SubwaySite.ServiceReferenceLogic.getStationRequest request);
        
        // CODEGEN: Generating message contract since element name line_Search from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLine", ReplyAction="*")]
        SubwaySite.ServiceReferenceLogic.getLineResponse getLine(SubwaySite.ServiceReferenceLogic.getLineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLine", ReplyAction="*")]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.getLineResponse> getLineAsync(SubwaySite.ServiceReferenceLogic.getLineRequest request);
        
        // CODEGEN: Generating message contract since element name line from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/closeLine", ReplyAction="*")]
        SubwaySite.ServiceReferenceLogic.closeLineResponse closeLine(SubwaySite.ServiceReferenceLogic.closeLineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/closeLine", ReplyAction="*")]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.closeLineResponse> closeLineAsync(SubwaySite.ServiceReferenceLogic.closeLineRequest request);
        
        // CODEGEN: Generating message contract since element name station from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/closeStation", ReplyAction="*")]
        SubwaySite.ServiceReferenceLogic.closeStationResponse closeStation(SubwaySite.ServiceReferenceLogic.closeStationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/closeStation", ReplyAction="*")]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.closeStationResponse> closeStationAsync(SubwaySite.ServiceReferenceLogic.closeStationRequest request);
        
        // CODEGEN: Generating message contract since element name admin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newAdmin", ReplyAction="*")]
        SubwaySite.ServiceReferenceLogic.newAdminResponse newAdmin(SubwaySite.ServiceReferenceLogic.newAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.newAdminResponse> newAdminAsync(SubwaySite.ServiceReferenceLogic.newAdminRequest request);
        
        // CODEGEN: Generating message contract since element name station from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newStation", ReplyAction="*")]
        SubwaySite.ServiceReferenceLogic.newStationResponse newStation(SubwaySite.ServiceReferenceLogic.newStationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newStation", ReplyAction="*")]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.newStationResponse> newStationAsync(SubwaySite.ServiceReferenceLogic.newStationRequest request);
        
        // CODEGEN: Generating message contract since element name line from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newLine", ReplyAction="*")]
        SubwaySite.ServiceReferenceLogic.newLineResponse newLine(SubwaySite.ServiceReferenceLogic.newLineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newLine", ReplyAction="*")]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.newLineResponse> newLineAsync(SubwaySite.ServiceReferenceLogic.newLineRequest request);
        
        // CODEGEN: Generating message contract since element name line from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_Line", ReplyAction="*")]
        SubwaySite.ServiceReferenceLogic.delete_LineResponse delete_Line(SubwaySite.ServiceReferenceLogic.delete_LineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_Line", ReplyAction="*")]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.delete_LineResponse> delete_LineAsync(SubwaySite.ServiceReferenceLogic.delete_LineRequest request);
        
        // CODEGEN: Generating message contract since element name station from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_Station", ReplyAction="*")]
        SubwaySite.ServiceReferenceLogic.delete_StationResponse delete_Station(SubwaySite.ServiceReferenceLogic.delete_StationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_Station", ReplyAction="*")]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.delete_StationResponse> delete_StationAsync(SubwaySite.ServiceReferenceLogic.delete_StationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSubwayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSubway", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.getSubwayRequestBody Body;
        
        public getSubwayRequest() {
        }
        
        public getSubwayRequest(SubwaySite.ServiceReferenceLogic.getSubwayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getSubwayRequestBody {
        
        public getSubwayRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSubwayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSubwayResponse", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.getSubwayResponseBody Body;
        
        public getSubwayResponse() {
        }
        
        public getSubwayResponse(SubwaySite.ServiceReferenceLogic.getSubwayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getSubwayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SubwaySite.ServiceReferenceLogic.Line[] getSubwayResult;
        
        public getSubwayResponseBody() {
        }
        
        public getSubwayResponseBody(SubwaySite.ServiceReferenceLogic.Line[] getSubwayResult) {
            this.getSubwayResult = getSubwayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStation", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.getStationRequestBody Body;
        
        public getStationRequest() {
        }
        
        public getStationRequest(SubwaySite.ServiceReferenceLogic.getStationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getStationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string station_Search;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SubwaySite.ServiceReferenceLogic.Line line;
        
        public getStationRequestBody() {
        }
        
        public getStationRequestBody(string station_Search, SubwaySite.ServiceReferenceLogic.Line line) {
            this.station_Search = station_Search;
            this.line = line;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStationResponse", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.getStationResponseBody Body;
        
        public getStationResponse() {
        }
        
        public getStationResponse(SubwaySite.ServiceReferenceLogic.getStationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getStationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SubwaySite.ServiceReferenceLogic.Station getStationResult;
        
        public getStationResponseBody() {
        }
        
        public getStationResponseBody(SubwaySite.ServiceReferenceLogic.Station getStationResult) {
            this.getStationResult = getStationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLine", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.getLineRequestBody Body;
        
        public getLineRequest() {
        }
        
        public getLineRequest(SubwaySite.ServiceReferenceLogic.getLineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getLineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string line_Search;
        
        public getLineRequestBody() {
        }
        
        public getLineRequestBody(string line_Search) {
            this.line_Search = line_Search;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLineResponse", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.getLineResponseBody Body;
        
        public getLineResponse() {
        }
        
        public getLineResponse(SubwaySite.ServiceReferenceLogic.getLineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getLineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SubwaySite.ServiceReferenceLogic.Line getLineResult;
        
        public getLineResponseBody() {
        }
        
        public getLineResponseBody(SubwaySite.ServiceReferenceLogic.Line getLineResult) {
            this.getLineResult = getLineResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeLineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="closeLine", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.closeLineRequestBody Body;
        
        public closeLineRequest() {
        }
        
        public closeLineRequest(SubwaySite.ServiceReferenceLogic.closeLineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class closeLineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SubwaySite.ServiceReferenceLogic.Line line;
        
        public closeLineRequestBody() {
        }
        
        public closeLineRequestBody(SubwaySite.ServiceReferenceLogic.Line line) {
            this.line = line;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeLineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="closeLineResponse", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.closeLineResponseBody Body;
        
        public closeLineResponse() {
        }
        
        public closeLineResponse(SubwaySite.ServiceReferenceLogic.closeLineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class closeLineResponseBody {
        
        public closeLineResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeStationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="closeStation", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.closeStationRequestBody Body;
        
        public closeStationRequest() {
        }
        
        public closeStationRequest(SubwaySite.ServiceReferenceLogic.closeStationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class closeStationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SubwaySite.ServiceReferenceLogic.Station station;
        
        public closeStationRequestBody() {
        }
        
        public closeStationRequestBody(SubwaySite.ServiceReferenceLogic.Station station) {
            this.station = station;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeStationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="closeStationResponse", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.closeStationResponseBody Body;
        
        public closeStationResponse() {
        }
        
        public closeStationResponse(SubwaySite.ServiceReferenceLogic.closeStationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class closeStationResponseBody {
        
        public closeStationResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class newAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="newAdmin", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.newAdminRequestBody Body;
        
        public newAdminRequest() {
        }
        
        public newAdminRequest(SubwaySite.ServiceReferenceLogic.newAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class newAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SubwaySite.ServiceReferenceLogic.Admin admin;
        
        public newAdminRequestBody() {
        }
        
        public newAdminRequestBody(SubwaySite.ServiceReferenceLogic.Admin admin) {
            this.admin = admin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class newAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="newAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.newAdminResponseBody Body;
        
        public newAdminResponse() {
        }
        
        public newAdminResponse(SubwaySite.ServiceReferenceLogic.newAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class newAdminResponseBody {
        
        public newAdminResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class newStationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="newStation", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.newStationRequestBody Body;
        
        public newStationRequest() {
        }
        
        public newStationRequest(SubwaySite.ServiceReferenceLogic.newStationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class newStationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SubwaySite.ServiceReferenceLogic.Station station;
        
        public newStationRequestBody() {
        }
        
        public newStationRequestBody(SubwaySite.ServiceReferenceLogic.Station station) {
            this.station = station;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class newStationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="newStationResponse", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.newStationResponseBody Body;
        
        public newStationResponse() {
        }
        
        public newStationResponse(SubwaySite.ServiceReferenceLogic.newStationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class newStationResponseBody {
        
        public newStationResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class newLineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="newLine", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.newLineRequestBody Body;
        
        public newLineRequest() {
        }
        
        public newLineRequest(SubwaySite.ServiceReferenceLogic.newLineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class newLineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SubwaySite.ServiceReferenceLogic.Line line;
        
        public newLineRequestBody() {
        }
        
        public newLineRequestBody(SubwaySite.ServiceReferenceLogic.Line line) {
            this.line = line;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class newLineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="newLineResponse", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.newLineResponseBody Body;
        
        public newLineResponse() {
        }
        
        public newLineResponse(SubwaySite.ServiceReferenceLogic.newLineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class newLineResponseBody {
        
        public newLineResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delete_LineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delete_Line", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.delete_LineRequestBody Body;
        
        public delete_LineRequest() {
        }
        
        public delete_LineRequest(SubwaySite.ServiceReferenceLogic.delete_LineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class delete_LineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SubwaySite.ServiceReferenceLogic.Line line;
        
        public delete_LineRequestBody() {
        }
        
        public delete_LineRequestBody(SubwaySite.ServiceReferenceLogic.Line line) {
            this.line = line;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delete_LineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delete_LineResponse", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.delete_LineResponseBody Body;
        
        public delete_LineResponse() {
        }
        
        public delete_LineResponse(SubwaySite.ServiceReferenceLogic.delete_LineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class delete_LineResponseBody {
        
        public delete_LineResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delete_StationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delete_Station", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.delete_StationRequestBody Body;
        
        public delete_StationRequest() {
        }
        
        public delete_StationRequest(SubwaySite.ServiceReferenceLogic.delete_StationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class delete_StationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SubwaySite.ServiceReferenceLogic.Station station;
        
        public delete_StationRequestBody() {
        }
        
        public delete_StationRequestBody(SubwaySite.ServiceReferenceLogic.Station station) {
            this.station = station;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delete_StationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delete_StationResponse", Namespace="http://tempuri.org/", Order=0)]
        public SubwaySite.ServiceReferenceLogic.delete_StationResponseBody Body;
        
        public delete_StationResponse() {
        }
        
        public delete_StationResponse(SubwaySite.ServiceReferenceLogic.delete_StationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class delete_StationResponseBody {
        
        public delete_StationResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceLogicSoapChannel : SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceLogicSoapClient : System.ServiceModel.ClientBase<SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap>, SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap {
        
        public WebServiceLogicSoapClient() {
        }
        
        public WebServiceLogicSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceLogicSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLogicSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLogicSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SubwaySite.ServiceReferenceLogic.getSubwayResponse SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.getSubway(SubwaySite.ServiceReferenceLogic.getSubwayRequest request) {
            return base.Channel.getSubway(request);
        }
        
        public SubwaySite.ServiceReferenceLogic.Line[] getSubway() {
            SubwaySite.ServiceReferenceLogic.getSubwayRequest inValue = new SubwaySite.ServiceReferenceLogic.getSubwayRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.getSubwayRequestBody();
            SubwaySite.ServiceReferenceLogic.getSubwayResponse retVal = ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).getSubway(inValue);
            return retVal.Body.getSubwayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.getSubwayResponse> SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.getSubwayAsync(SubwaySite.ServiceReferenceLogic.getSubwayRequest request) {
            return base.Channel.getSubwayAsync(request);
        }
        
        public System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.getSubwayResponse> getSubwayAsync() {
            SubwaySite.ServiceReferenceLogic.getSubwayRequest inValue = new SubwaySite.ServiceReferenceLogic.getSubwayRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.getSubwayRequestBody();
            return ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).getSubwayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SubwaySite.ServiceReferenceLogic.getStationResponse SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.getStation(SubwaySite.ServiceReferenceLogic.getStationRequest request) {
            return base.Channel.getStation(request);
        }
        
        public SubwaySite.ServiceReferenceLogic.Station getStation(string station_Search, SubwaySite.ServiceReferenceLogic.Line line) {
            SubwaySite.ServiceReferenceLogic.getStationRequest inValue = new SubwaySite.ServiceReferenceLogic.getStationRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.getStationRequestBody();
            inValue.Body.station_Search = station_Search;
            inValue.Body.line = line;
            SubwaySite.ServiceReferenceLogic.getStationResponse retVal = ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).getStation(inValue);
            return retVal.Body.getStationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.getStationResponse> SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.getStationAsync(SubwaySite.ServiceReferenceLogic.getStationRequest request) {
            return base.Channel.getStationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.getStationResponse> getStationAsync(string station_Search, SubwaySite.ServiceReferenceLogic.Line line) {
            SubwaySite.ServiceReferenceLogic.getStationRequest inValue = new SubwaySite.ServiceReferenceLogic.getStationRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.getStationRequestBody();
            inValue.Body.station_Search = station_Search;
            inValue.Body.line = line;
            return ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).getStationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SubwaySite.ServiceReferenceLogic.getLineResponse SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.getLine(SubwaySite.ServiceReferenceLogic.getLineRequest request) {
            return base.Channel.getLine(request);
        }
        
        public SubwaySite.ServiceReferenceLogic.Line getLine(string line_Search) {
            SubwaySite.ServiceReferenceLogic.getLineRequest inValue = new SubwaySite.ServiceReferenceLogic.getLineRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.getLineRequestBody();
            inValue.Body.line_Search = line_Search;
            SubwaySite.ServiceReferenceLogic.getLineResponse retVal = ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).getLine(inValue);
            return retVal.Body.getLineResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.getLineResponse> SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.getLineAsync(SubwaySite.ServiceReferenceLogic.getLineRequest request) {
            return base.Channel.getLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.getLineResponse> getLineAsync(string line_Search) {
            SubwaySite.ServiceReferenceLogic.getLineRequest inValue = new SubwaySite.ServiceReferenceLogic.getLineRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.getLineRequestBody();
            inValue.Body.line_Search = line_Search;
            return ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).getLineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SubwaySite.ServiceReferenceLogic.closeLineResponse SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.closeLine(SubwaySite.ServiceReferenceLogic.closeLineRequest request) {
            return base.Channel.closeLine(request);
        }
        
        public void closeLine(SubwaySite.ServiceReferenceLogic.Line line) {
            SubwaySite.ServiceReferenceLogic.closeLineRequest inValue = new SubwaySite.ServiceReferenceLogic.closeLineRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.closeLineRequestBody();
            inValue.Body.line = line;
            SubwaySite.ServiceReferenceLogic.closeLineResponse retVal = ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).closeLine(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.closeLineResponse> SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.closeLineAsync(SubwaySite.ServiceReferenceLogic.closeLineRequest request) {
            return base.Channel.closeLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.closeLineResponse> closeLineAsync(SubwaySite.ServiceReferenceLogic.Line line) {
            SubwaySite.ServiceReferenceLogic.closeLineRequest inValue = new SubwaySite.ServiceReferenceLogic.closeLineRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.closeLineRequestBody();
            inValue.Body.line = line;
            return ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).closeLineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SubwaySite.ServiceReferenceLogic.closeStationResponse SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.closeStation(SubwaySite.ServiceReferenceLogic.closeStationRequest request) {
            return base.Channel.closeStation(request);
        }
        
        public void closeStation(SubwaySite.ServiceReferenceLogic.Station station) {
            SubwaySite.ServiceReferenceLogic.closeStationRequest inValue = new SubwaySite.ServiceReferenceLogic.closeStationRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.closeStationRequestBody();
            inValue.Body.station = station;
            SubwaySite.ServiceReferenceLogic.closeStationResponse retVal = ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).closeStation(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.closeStationResponse> SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.closeStationAsync(SubwaySite.ServiceReferenceLogic.closeStationRequest request) {
            return base.Channel.closeStationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.closeStationResponse> closeStationAsync(SubwaySite.ServiceReferenceLogic.Station station) {
            SubwaySite.ServiceReferenceLogic.closeStationRequest inValue = new SubwaySite.ServiceReferenceLogic.closeStationRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.closeStationRequestBody();
            inValue.Body.station = station;
            return ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).closeStationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SubwaySite.ServiceReferenceLogic.newAdminResponse SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.newAdmin(SubwaySite.ServiceReferenceLogic.newAdminRequest request) {
            return base.Channel.newAdmin(request);
        }
        
        public void newAdmin(SubwaySite.ServiceReferenceLogic.Admin admin) {
            SubwaySite.ServiceReferenceLogic.newAdminRequest inValue = new SubwaySite.ServiceReferenceLogic.newAdminRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.newAdminRequestBody();
            inValue.Body.admin = admin;
            SubwaySite.ServiceReferenceLogic.newAdminResponse retVal = ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).newAdmin(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.newAdminResponse> SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.newAdminAsync(SubwaySite.ServiceReferenceLogic.newAdminRequest request) {
            return base.Channel.newAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.newAdminResponse> newAdminAsync(SubwaySite.ServiceReferenceLogic.Admin admin) {
            SubwaySite.ServiceReferenceLogic.newAdminRequest inValue = new SubwaySite.ServiceReferenceLogic.newAdminRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.newAdminRequestBody();
            inValue.Body.admin = admin;
            return ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).newAdminAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SubwaySite.ServiceReferenceLogic.newStationResponse SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.newStation(SubwaySite.ServiceReferenceLogic.newStationRequest request) {
            return base.Channel.newStation(request);
        }
        
        public void newStation(SubwaySite.ServiceReferenceLogic.Station station) {
            SubwaySite.ServiceReferenceLogic.newStationRequest inValue = new SubwaySite.ServiceReferenceLogic.newStationRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.newStationRequestBody();
            inValue.Body.station = station;
            SubwaySite.ServiceReferenceLogic.newStationResponse retVal = ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).newStation(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.newStationResponse> SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.newStationAsync(SubwaySite.ServiceReferenceLogic.newStationRequest request) {
            return base.Channel.newStationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.newStationResponse> newStationAsync(SubwaySite.ServiceReferenceLogic.Station station) {
            SubwaySite.ServiceReferenceLogic.newStationRequest inValue = new SubwaySite.ServiceReferenceLogic.newStationRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.newStationRequestBody();
            inValue.Body.station = station;
            return ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).newStationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SubwaySite.ServiceReferenceLogic.newLineResponse SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.newLine(SubwaySite.ServiceReferenceLogic.newLineRequest request) {
            return base.Channel.newLine(request);
        }
        
        public void newLine(SubwaySite.ServiceReferenceLogic.Line line) {
            SubwaySite.ServiceReferenceLogic.newLineRequest inValue = new SubwaySite.ServiceReferenceLogic.newLineRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.newLineRequestBody();
            inValue.Body.line = line;
            SubwaySite.ServiceReferenceLogic.newLineResponse retVal = ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).newLine(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.newLineResponse> SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.newLineAsync(SubwaySite.ServiceReferenceLogic.newLineRequest request) {
            return base.Channel.newLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.newLineResponse> newLineAsync(SubwaySite.ServiceReferenceLogic.Line line) {
            SubwaySite.ServiceReferenceLogic.newLineRequest inValue = new SubwaySite.ServiceReferenceLogic.newLineRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.newLineRequestBody();
            inValue.Body.line = line;
            return ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).newLineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SubwaySite.ServiceReferenceLogic.delete_LineResponse SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.delete_Line(SubwaySite.ServiceReferenceLogic.delete_LineRequest request) {
            return base.Channel.delete_Line(request);
        }
        
        public void delete_Line(SubwaySite.ServiceReferenceLogic.Line line) {
            SubwaySite.ServiceReferenceLogic.delete_LineRequest inValue = new SubwaySite.ServiceReferenceLogic.delete_LineRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.delete_LineRequestBody();
            inValue.Body.line = line;
            SubwaySite.ServiceReferenceLogic.delete_LineResponse retVal = ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).delete_Line(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.delete_LineResponse> SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.delete_LineAsync(SubwaySite.ServiceReferenceLogic.delete_LineRequest request) {
            return base.Channel.delete_LineAsync(request);
        }
        
        public System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.delete_LineResponse> delete_LineAsync(SubwaySite.ServiceReferenceLogic.Line line) {
            SubwaySite.ServiceReferenceLogic.delete_LineRequest inValue = new SubwaySite.ServiceReferenceLogic.delete_LineRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.delete_LineRequestBody();
            inValue.Body.line = line;
            return ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).delete_LineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SubwaySite.ServiceReferenceLogic.delete_StationResponse SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.delete_Station(SubwaySite.ServiceReferenceLogic.delete_StationRequest request) {
            return base.Channel.delete_Station(request);
        }
        
        public void delete_Station(SubwaySite.ServiceReferenceLogic.Station station) {
            SubwaySite.ServiceReferenceLogic.delete_StationRequest inValue = new SubwaySite.ServiceReferenceLogic.delete_StationRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.delete_StationRequestBody();
            inValue.Body.station = station;
            SubwaySite.ServiceReferenceLogic.delete_StationResponse retVal = ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).delete_Station(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.delete_StationResponse> SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap.delete_StationAsync(SubwaySite.ServiceReferenceLogic.delete_StationRequest request) {
            return base.Channel.delete_StationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SubwaySite.ServiceReferenceLogic.delete_StationResponse> delete_StationAsync(SubwaySite.ServiceReferenceLogic.Station station) {
            SubwaySite.ServiceReferenceLogic.delete_StationRequest inValue = new SubwaySite.ServiceReferenceLogic.delete_StationRequest();
            inValue.Body = new SubwaySite.ServiceReferenceLogic.delete_StationRequestBody();
            inValue.Body.station = station;
            return ((SubwaySite.ServiceReferenceLogic.WebServiceLogicSoap)(this)).delete_StationAsync(inValue);
        }
    }
}
