//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.ServiceReferenceData {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceData.WebServiceDataSoap")]
    public interface WebServiceDataSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/add", ReplyAction="*")]
        void add();
        
        // CODEGEN: Generating message contract since element name Searching_For_All_UsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Searching_For_All_Users", ReplyAction="*")]
        Logic.ServiceReferenceData.Searching_For_All_UsersResponse Searching_For_All_Users(Logic.ServiceReferenceData.Searching_For_All_UsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/create", ReplyAction="*")]
        void create();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Searching_For_All_UsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Searching_For_All_Users", Namespace="http://tempuri.org/", Order=0)]
        public Logic.ServiceReferenceData.Searching_For_All_UsersRequestBody Body;
        
        public Searching_For_All_UsersRequest() {
        }
        
        public Searching_For_All_UsersRequest(Logic.ServiceReferenceData.Searching_For_All_UsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Searching_For_All_UsersRequestBody {
        
        public Searching_For_All_UsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Searching_For_All_UsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Searching_For_All_UsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Logic.ServiceReferenceData.Searching_For_All_UsersResponseBody Body;
        
        public Searching_For_All_UsersResponse() {
        }
        
        public Searching_For_All_UsersResponse(Logic.ServiceReferenceData.Searching_For_All_UsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Searching_For_All_UsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Logic.ServiceReferenceData.ArrayOfString Searching_For_All_UsersResult;
        
        public Searching_For_All_UsersResponseBody() {
        }
        
        public Searching_For_All_UsersResponseBody(Logic.ServiceReferenceData.ArrayOfString Searching_For_All_UsersResult) {
            this.Searching_For_All_UsersResult = Searching_For_All_UsersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceDataSoapChannel : Logic.ServiceReferenceData.WebServiceDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceDataSoapClient : System.ServiceModel.ClientBase<Logic.ServiceReferenceData.WebServiceDataSoap>, Logic.ServiceReferenceData.WebServiceDataSoap {
        
        public WebServiceDataSoapClient() {
        }
        
        public WebServiceDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void add() {
            base.Channel.add();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logic.ServiceReferenceData.Searching_For_All_UsersResponse Logic.ServiceReferenceData.WebServiceDataSoap.Searching_For_All_Users(Logic.ServiceReferenceData.Searching_For_All_UsersRequest request) {
            return base.Channel.Searching_For_All_Users(request);
        }
        
        public Logic.ServiceReferenceData.ArrayOfString Searching_For_All_Users() {
            Logic.ServiceReferenceData.Searching_For_All_UsersRequest inValue = new Logic.ServiceReferenceData.Searching_For_All_UsersRequest();
            inValue.Body = new Logic.ServiceReferenceData.Searching_For_All_UsersRequestBody();
            Logic.ServiceReferenceData.Searching_For_All_UsersResponse retVal = ((Logic.ServiceReferenceData.WebServiceDataSoap)(this)).Searching_For_All_Users(inValue);
            return retVal.Body.Searching_For_All_UsersResult;
        }
        
        public void create() {
            base.Channel.create();
        }
    }
}
